import { View } from "react-native-reanimated/lib/typescript/Animated";

export default {
  loginTitle: 'Login into Your Account',
  loginSubtitle: 'See what is going on with your business',
  mobilePlaceholder: 'Mobile Number',
  passwordPlaceholder: 'Password',
  forgotPassword: 'Forgot Password',
  offlineForm: 'Offline Form',
  loginButton: 'Login',
  offlineButton: 'Offline',
  errorMissingFields: 'Please enter both mobile number and password.',
  errorInvalidMobile: 'Please enter a valid 10-digit mobile number.',
  loginFailed: 'Login Failed',
  dashboard: "Dashboard",
  generateHealthReport: "Generate Health Report",
  healthReportList: "Health Report List",
  dispatchReportList: "Dispatch Report List",
  dispatchTruckList: "Dispatch Truck List",
  receiveTruckList: "Receive Truck List",
  reimbursementForm: "Reimbursement Form",
  savedReport: "Saved Report",
  languageSelector: "Language Selector",
  offlineDashboard: "Offline Dashboard",
  reportOffline: "Offline Report",
  receivingPendingTruck: "Receiving Pending Truck",
  receivedTruck: "Received Truck",
  requestReimbursement: "Request Reimbursement",
  pendingPayment: "Pending Payment",
paidPayment: "Paid Payment",
paymentDeclined: "Payment Declined",
Count : "Count",
SelectedCompany :  "Select Company",
    SelectedBranch : "Select Branch",
    SelectedDistrict : "Select District",
    Next : "Next",
    Previous : "Previous",


      TruckNumber: "Truck Number",
      Grossweight : "Gross Weight (KG)",
       Netweight : "Net Weight (KG)",
      Tareweight: "Tare Weight (KG)",
      selecteddate: "Select Date",
      Bagcount : "Bag Count",
      size : "Size",
      stainingColor : "Staining Color",
      stainingcolorpercent : "Staining Color Percentage",
       BlacksmutOnion : "Black smut Onion",
       BlacksmutOnionpercent : "Black smut Onion Percentage",
       SproutedOnion : "Sprouted Onion",
       SproutedOnionpercent : "Sprouted Onion Percentage",
      SpoiledOnion: "Spoiled Onion",
      SpoiledOnionpercent : "Spoiled Onion Percentage",
      Onionskin : "Onion Skin",
      Onionskinsinglepercent : "Onion Skin Single Percentage",
      Double : "Double",
      Single : "Single",
      Moisture : "Moisture",
       Dry: "Dry",
      Wet : "Wet",
      Moisturewetpercent : "Moisture Wet Percentage",
      spoiledperecent : "Spoiled Percentage",
      typecomment : "Type of Comment",
      submit : "Submit",
       branchpersonname: "Branch Person's Name",
       Spoiled : "Spoiled",
       CaptureImage : "Capture Image",
       PickfromCamera : "Pick from Camera",
       SearchAssayerNameanddate : " Search Assayer Name and date",
       assyarerName : "Assayer Name",
       Date : "Date",
       ViewReport : "View Report",
       RecieveHealthReportDetails : "Receive Health Report Details",
       ApprovalStatus : "Approval Status", 
       images : "Images",
       Close : "Close",
       DispatchBranch : "Dispatch Branch",
       District : "District",
       Quantity : "Quantity",
       Transporter : "Transporter",
       DispatchType : "Dispatch Type",
       SelectDate : "Select Date",
       Billtype : "Bill Type",
       selectBilltype : "Select Bill Type",
       StartTripReading : "Start Trip Reading",
        EndTripReading : "End Trip Reading",
        Amount : "Amount",
        purpose : "Purpose",
        Camera : "Camera",
        Gallery : "Gallery",
        GotoDhashboard : "Go to Dashboard",
        View : "View",
        ReimbursmentList : "Reimbursement List", 
        ReportOffline : "ReportOffline",
        OfflineSavedForms : "Offline Saved Forms",
        Noofflineformsfound :   "No offline forms found",
        Enterotp : "Enter OTP",
        RequestOTP : "Request OTP",
        NewPassword : "New Password",
        confirmPassword : "Confirm Password",
        ResetPassword : "Reset Password",
        BacktoLogin : " Back to Login",
        Search : "Search"
    
    

  };
  