export default {
  loginTitle: 'अपने खाते में लॉगिन करें',
    loginSubtitle: 'अपने व्यवसाय में क्या हो रहा है देखें',
    mobilePlaceholder: 'मोबाइल नंबर',
    passwordPlaceholder: 'पासवर्ड',
    forgotPassword: 'पासवर्ड भूल गए?',
    offlineForm: 'ऑफलाइन फॉर्म',
    loginButton: 'लॉगिन',
    offlineButton: 'ऑफलाइन',
    errorMissingFields: 'कृपया मोबाइल नंबर और पासवर्ड दर्ज करें।',
    errorInvalidMobile: 'कृपया एक मान्य 10-अंकीय मोबाइल नंबर दर्ज करें।',
    loginFailed: 'लॉगिन विफल रहा',
    dashboard: "डैशबोर्ड",
    generateHealthReport: "हेल्थ रिपोर्ट बनाएं",
    healthReportList: "हेल्थ रिपोर्ट सूची",
    dispatchReportList: "डिस्पैच रिपोर्ट सूची",
    dispatchTruckList: "डिस्पैच ट्रक सूची",
    receiveTruckList: "रीसीव ट्रक सूची",
    reimbursementForm: "रियम्बर्समेंट फ़ॉर्म",
    savedReport: "सेव की गई रिपोर्ट",
    languageSelector: "भाषा चयन",
    offlineDashboard: "ऑफ़लाइन डैशबोर्ड",
    reportOffline: "ऑफ़लाइन रिपोर्ट",
    receivingPendingTruck: "रिसीविंग पेंडिंग ट्रक",
    receivedTruck: "प्राप्त ट्रक",
    requestReimbursement: "रियम्बर्समेंट का अनुरोध करें",
    pendingPayment: "लंबित भुगतान",
    paidPayment: "भुगतान हो चुका है",
    paymentDeclined: "भुगतान अस्वीकृत",
    Count : "कुल संख्या",
    SelectedCompany :  "कंपनी चुनें",
    SelectedBranch : "शाखा चुनें",
    SelectedDistrict : "जिला चुनें",
    Next : "अगला",
    Previous : "पिछला",
    TruckNumber : "ट्रक नंबर",
    Grossweight : "कुल वजन (किलोग्राम)",
    Netweight : "शुद्ध वजन (किलोग्राम)",
    Tareweight : "वाहन का वजन (किलोग्राम)",
    selecteddate : "तारीख का चयन करें",
    Bagcount : "बैग की संख्या",
    size : "आकार",
    stainingColor : "दाग का रंग",
    stainingcolorpercent : "दाग का रंग प्रतिशत",
    BlacksmutOnion : "काले धब्बे",
    BlacksmutOnionpercent : "काले धब्बे प्रतिशत",
    SproutedOnion : "अंकुरित प्याज",
    SproutedOnionpercent : "अंकुरित प्याज प्रतिशत",
    SpoiledOnion : "सड़ा हुआ प्याज",
    SpoiledOnionpercent : "सड़ा हुआ प्याज प्रतिशत",
    Onionskin : "प्याज की त्वचा",
    Onionskinsinglepercent : "सिंगल प्याज की त्वचा प्रतिशत",
    Double : "डबल",
    Single : "सिंगल",
    Moisture : "नमी",
    Dry : "सूखा",
    Wet : "गीला",
    Moisturewetpercent : "नमी गीला प्रतिशत",
    spoiledperecent : "सड़ने की प्रतिशत",
    typecomment : "टिप्पणी का प्रकार",
    submit : "जमा करें",
    branchpersonname : "शाखा व्यक्ति का नाम",
    Spoiled : "सड़ा हुआ",
    CaptureImage : "छवि कैप्चर करें",
    PickfromCamera  : "कैमरा से चुनें",
    SearchAssayerNameanddate : "अस्सेयर का नाम और दिनांक खोजें",
    assyarerName : "अस्सेयर का नाम",
    Date : "तारीख",
    ViewReport : "रिपोर्ट देखें",
    RecieveHealthReportDetails : "हेल्थ रिपोर्ट विवरण प्राप्त करें",
    ApprovalStatus : "मंज़ूरी की स्थिति",
    images : "छवियाँ",
    Close : "बंद करें",
    DispatchBranch : "डिस्पैच शाखा",
    District : "जिला",
    Quantity : "मात्रा",
    Transporter : "ट्रांसपोर्टर",
    DispatchType : "डिस्पैच प्रकार",
    SelectDate : "तारीख का चयन करें",
    Billtype : "बिल का प्रकार",
    selectBilltype : "बिल का प्रकार चुनें",
    StartTripReading: "यात्रा शुरू करें",  
    EndTripReading: "यात्रा समाप्त करें",
    Amount : "राशि",
    purpose : "उद्देश्य",
    Camera : "कैमरा",
    Gallery : "गैलरी",
    GotoDhashboard : "डैशबोर्ड पर जाएं",
    View : "देखें",
    ReimbursmentList : "रियम्बर्समेंट सूची",
    Reportoffline : "ऑफ़लाइन रिपोर्ट",
    OfflineSavedForms  : "ऑफलाइन सहेजे गए फ़ॉर्म",
    Noofflineformsfound  : "कोई ऑफलाइन फ़ॉर्म उपलब्ध नहीं है",
    Enterotp : "ओटीपी दर्ज करें",
    RequestOTP  : "ओटीपी का अनुरोध करें",
    NewPassword : "नया पासवर्ड",
    confirmPassword : "पासवर्ड की पुष्टि करें",
    ResetPassword :  "पासवर्ड रीसेट करें",
    BacktoLogin : " लॉगिन पर वापस जाएं",
    Search : "खोज"
    
  
}