export default {
  loginTitle: 'तुमच्या खात्यात लॉगिन करा',
  loginSubtitle: 'तुमच्या व्यवसायात काय चालले आहे ते पाहा',
  mobilePlaceholder: 'मोबाईल नंबर',
  passwordPlaceholder: 'पासवर्ड',
  forgotPassword: 'पासवर्ड विसरलात?',
  offlineForm: 'ऑफलाइन फॉर्म',
  loginButton: 'लॉगिन',
  offlineButton: 'ऑफलाइन',
  errorMissingFields: 'कृपया मोबाईल नंबर आणि पासवर्ड टाका.',
  errorInvalidMobile: 'कृपया वैध 10-अंकी मोबाईल नंबर टाका.',
  loginFailed: 'लॉगिन अयशस्वी',
  dashboard: 'डॅशबोर्ड',
  generateHealthReport: 'हेल्थ रिपोर्ट तयार करा',
  healthReportList: 'हेल्थ रिपोर्ट यादी',
  dispatchReportList: 'डिस्पॅच रिपोर्ट यादी',
  dispatchTruckList: 'डिस्पॅच ट्रक यादी',
  receiveTruckList: 'रीसीव्ह ट्रक यादी',
  reimbursementForm: 'रिम्बर्समेंट फॉर्म',
  savedReport: 'सेव्ह केलेले रिपोर्ट',
  languageSelector: 'भाषा निवडा',
  offlineDashboard: 'ऑफलाइन डॅशबोर्ड',
  reportOffline: 'ऑफलाइन रिपोर्ट',
  receivingPendingTruck: 'प्रलंबित रीसीव्ह ट्रक',
  receivedTruck: 'रीसीव्ह केलेले ट्रक',
  requestReimbursement: 'रिम्बर्समेंटची विनंती करा',
  pendingPayment: 'प्रलंबित पेमेंट',
  paidPayment: 'पेमेंट झाले आहे',
  paymentDeclined: 'पेमेंट नाकारले',
  Count: 'एकूण संख्या',
  SelectedCompany: 'कंपनी निवडा',
  SelectedBranch: 'शाखा निवडा',
  SelectedDistrict: 'जिल्हा निवडा',
  Next: 'पुढे',
  Previous: 'मागे',
  TruckNumber: 'ट्रक क्रमांक',
  Grossweight: 'एकूण वजन (किलो)',
  Netweight: 'निव्वळ वजन (किलो)',
  Tareweight: 'वाहनाचे वजन (किलो)',
  selecteddate: 'तारीख निवडा',
  Bagcount: 'बॅगची संख्या',
  size: 'आकार',
  stainingColor: 'डागाचा रंग',
  stainingcolorpercent: 'डागाचा रंग टक्केवारी',
  BlacksmutOnion: 'काळे डाग',
  BlacksmutOnionpercent: 'काळ्या डागांची टक्केवारी',
  SproutedOnion: 'अंकुरलेले कांदे',
  SproutedOnionpercent: 'अंकुरलेले कांदे टक्केवारी',
  SpoiledOnion: 'बिघडलेला कांदा',
  SpoiledOnionpercent: 'बिघडलेले कांदे टक्केवारी',
  Onionskin: 'कांद्याची साली',
  Onionskinsinglepercent: 'एकेरी सालीची टक्केवारी',
  Double: 'डबल',
  Single: 'सिंगल',
  Moisture: 'आर्द्रता',
  Dry: 'कोरडे',
  Wet: 'ओले',
  Moisturewetpercent: 'ओलसरतेची टक्केवारी',
  spoiledperecent: 'बिघडण्याची टक्केवारी',
  typecomment: 'टिप्पणीचा प्रकार',
  submit: 'सबमिट करा',
  branchpersonname: 'शाखेतील व्यक्तीचे नाव',
  Spoiled: 'बिघडलेले',
  CaptureImage: 'प्रतिमा कैद करा',
  PickfromCamera: 'कॅमेरा वापरा',
  SearchAssayerNameanddate: 'अस्सेयरचे नाव आणि तारीख शोधा',
  assyarerName: 'अस्सेयरचे नाव',
  Date: 'तारीख',
  ViewReport: 'रिपोर्ट पहा',
  RecieveHealthReportDetails: 'हेल्थ रिपोर्ट तपशील पहा',
  ApprovalStatus: 'मंजुरीची स्थिती',
  images: 'प्रतिमा',
  Close: 'बंद करा',
  DispatchBranch: 'डिस्पॅच शाखा',
  District: 'जिल्हा',
  Quantity: 'प्रमाण',
  Transporter: 'वाहतूकदार',
  DispatchType: 'डिस्पॅच प्रकार',
  SelectDate: 'तारीख निवडा',
  Billtype: 'बिल प्रकार',
  selectBilltype: 'बिल प्रकार निवडा',
  StartTripReading: 'प्रवास सुरू करा',
  EndTripReading: 'प्रवास समाप्त करा',
  Amount: 'रक्कम',
  purpose: 'उद्देश',
  Camera: 'कॅमेरा',
  Gallery: 'गॅलरी',
  GotoDhashboard: 'डॅशबोर्डवर जा',
  View: 'पहा',
  ReimbursmentList: 'रिम्बर्समेंट यादी',
  Reportoffline: 'ऑफलाइन रिपोर्ट',
  OfflineSavedForms : "ऑफलाइन जतन केलेले फॉर्म",
  Enterotp : "ओटीपी प्रविष्ट करा",
  RequestOTP  : "ओटीपीची विनंती करा",
  NewPassword : "नवीन पासवर्ड",
  confirmPassword : "पासवर्डची पुष्टी करा",
  ResetPassword  : "पासवर्ड रीसेट करा",
  BacktoLogin : "लॉगिनवर परत जा",
  Search : "शोध"
};
