rootProject.name = 'QRCodeScannerApp'
include ':app'

// React Native Gradle Plugin
includeBuild('../node_modules/react-native-gradle-plugin') {
    name = 'ReactNativeGradlePlugin'
}

// Expo Autolinking (agar folder exist kare)
def expoAutolinkingPath = new File(rootDir, "../node_modules/expo-modules-autolinking/android")
if (expoAutolinkingPath.exists()) {
    apply from: new File(expoAutolinkingPath, "expo-autolinking.gradle")
} else {
    println("Expo autolinking plugin not found at: " + expoAutolinkingPath)
}
